// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmsGhUcv-yT16PmUHQkKxCpGhaRXXVe0w',
    appId: '1:509007349746:web:b5158d245dc565e2804d6b',
    messagingSenderId: '509007349746',
    projectId: 'data-f546e',
    authDomain: 'data-f546e.firebaseapp.com',
    storageBucket: 'data-f546e.appspot.com',
    measurementId: 'G-CYNQ9GVDN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCJV1CufRYf7vv7flC80lc--PAr2MFaiw',
    appId: '1:509007349746:android:03c4fa9398ed2ce8804d6b',
    messagingSenderId: '509007349746',
    projectId: 'data-f546e',
    storageBucket: 'data-f546e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXDRK0R-8E4_JTCrEhFPI0lsnUVPLyAnc',
    appId: '1:509007349746:ios:d3b2f5b2615121e6804d6b',
    messagingSenderId: '509007349746',
    projectId: 'data-f546e',
    storageBucket: 'data-f546e.appspot.com',
    androidClientId: '509007349746-k2e5l031v9d9u12kg86cbsnls6mvok8h.apps.googleusercontent.com',
    iosClientId: '509007349746-hu0ktsbgtt460j5v39v9u4kbtb9vhvur.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterauth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmsGhUcv-yT16PmUHQkKxCpGhaRXXVe0w',
    appId: '1:509007349746:web:6d2c11ff0bd57ba3804d6b',
    messagingSenderId: '509007349746',
    projectId: 'data-f546e',
    authDomain: 'data-f546e.firebaseapp.com',
    storageBucket: 'data-f546e.appspot.com',
    measurementId: 'G-WD5HSYDB9N',
  );
}
